// import { StrictMode } from 'react'
// import { createRoot } from 'react-dom/client'
// import './index.css'
// import App from './App.jsx'
// import Contact from './components/Contact.jsx'
// import About from './components/About.jsx'
// import Layout from './components/Layout.jsx'
// import {createBrowserRouter, RouterProvider} from 'react-router-dom'